name: Lint
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"

jobs:
  lint:
    name: Shellcheck and Shell Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: asdf_install
        uses: asdf-vm/actions/install@v3
      - name: Shellcheck
        run: shellcheck -x bin/* -P lib/
      - name: Shell Format - Validate
        run: shfmt -d -i 2 -ci bin/* lib/*
